### ISSUE TITLE
Glowroot agent 0.13.6 version is not working with the Spring boot app 2.5.12 

### ISSUE THREAD

**Issue by madhurikolla** [glowroot/glowroot#930]
hi @trask , 

I am getting below exception when tried to connect with the spring boot app version 2.5.12 - 

```
2022-04-19 05:50:42.636 ERROR o.g.agent.impl.BytecodeServiceImpl - org/glowroot/agent/shaded/io/netty/util/internal/logging/JdkLogger 
java.lang.NoClassDefFoundError: org/glowroot/agent/shaded/io/netty/util/internal/logging/JdkLogger 
        at org.glowroot.agent.shaded.io.netty.util.internal.logging.JdkLoggerFactory.newInstance(JdkLoggerFactory.java:39) 
        at org.glowroot.agent.shaded.io.netty.util.internal.logging.InternalLoggerFactory.newDefaultFactory(InternalLoggerFactory.java:54) 
        at org.glowroot.agent.shaded.io.netty.util.internal.logging.InternalLoggerFactory.getDefaultFactory(InternalLoggerFactory.java:67) 
        at org.glowroot.agent.shaded.io.netty.util.internal.logging.InternalLoggerFactory.getInstance(InternalLoggerFactory.java:93) 
        at org.glowroot.agent.shaded.io.netty.util.internal.logging.InternalLoggerFactory.getInstance(InternalLoggerFactory.java:86) 
        at org.glowroot.agent.shaded.io.netty.util.ResourceLeakDetector.<clinit>(ResourceLeakDetector.java:94) 
        at org.glowroot.agent.shaded.io.netty.buffer.AbstractByteBufAllocator.<clinit>(AbstractByteBufAllocator.java:34) 
        at org.glowroot.agent.init.NettyInit.run(NettyInit.java:63) 
        at org.glowroot.agent.init.NonEmbeddedGlowrootAgentInit$1.run(NonEmbeddedGlowrootAgentInit.java:122) 
        at org.glowroot.agent.impl.BytecodeServiceImpl.enteringMainMethod(BytecodeServiceImpl.java:255) 
        at org.glowroot.agent.impl.BytecodeServiceImpl.enteringMainMethod(BytecodeServiceImpl.java:77) 
        at org.glowroot.agent.bytecode.api.Bytecode.enteringMainMethod(Bytecode.java:32) 
        at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java) 
```

I tried adding the argument like -  -Dorg.glowroot.agent.shaded.io.netty.allocator.maxOrder=9 and Now I am getting below error. here are the logs - 

`04-May-2022 15:14:31.033 SEVERE [main] org.apache.catalina.startup.ContextConfig.processAnnotationsJar Unable to process Jar entry [org/glowroot/agent/shaded/io/netty/util/internal/logging/Log4J2Logger.class] from Jar [file:/opt/app/workload/tapm/hfrapm-agent-0.13.6-172.cl.jar] for annotationsjava.util.zip.ZipException: invalid LOC header (bad signature)at java.util.zip.ZipFile.read(Native Method)at java.util.zip.ZipFile.access$1400(ZipFile.java:60)at java.util.zip.ZipFile$ZipFileInputStream.read(ZipFile.java:734)at java.util.zip.ZipFile$ZipFileInflaterInputStream.fill(ZipFile.java:434)at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)at java.io.BufferedInputStream.read(BufferedInputStream.java:265)at java.io.DataInputStream.readInt(DataInputStream.java:387)at org.apache.tomcat.util.bcel.classfile.ClassParser.readID(ClassParser.java:199)at org.apache.tomcat.util.bcel.classfile.ClassParser.parse(ClassParser.java:78)at org.apache.catalina.startup.ContextConfig.processAnnotationsStream(ContextConfig.java:2351)at org.apache.catalina.startup.ContextConfig.processAnnotationsJar(ContextConfig.java:2298)at org.apache.catalina.startup.ContextConfig.processAnnotationsUrl(ContextConfig.java:2268)at org.apache.catalina.startup.ContextConfig.scanWebXmlFragment(ContextConfig.java:2173)at org.apache.catalina.startup.ContextConfig.processAnnotations(ContextConfig.java:2153)`

Can you please assist us on this issue ?

Thanks,
Madhuri

**Comment by Never-lab** [comment]
A few strong signals in the report point to **agent packaging / deployment**, not “Spring Boot 2.5.12 is incompatible with Glowroot 0.13.6.”

### 1. That JAR is not the official agent name

Official 0.13.6 ships as `glowroot.jar` inside [`glowroot-0.13.6-dist.zip`](https://github.com/glowroot/glowroot/releases/tag/v0.13.6).

Your path shows:

`hfrapm-agent-0.13.6-172.cl.jar`

That looks like a **custom / renamed / rebuilt** agent. A `NoClassDefFoundError` for  
`org.glowroot.agent.shaded.io.netty.util.internal.logging.JdkLogger` inside *shaded* Netty usually means the fat jar is **incomplete or incorrectly shaded**, not that Spring Boot can’t load Netty.

### 2. `ZipException: invalid LOC header (bad signature)`

Tomcat is running `ContextConfig.processAnnotationsJar` on that agent jar. That means the jar is on a path Tomcat **scans as an application/library jar** (e.g. dropped under the webapp / shared lib), **or** the file on disk is **corrupt**.

Glowroot must be attached only as:

```text
-javaagent:/path/to/official/glowroot.jar
```

Do **not** put the agent jar in `WEB-INF/lib`, the WAR, or a Tomcat lib directory that gets annotation-scanned. A corrupt or partially copied jar also produces exactly this ZipException.

The `-Dorg.glowroot.agent.shaded.io.netty.allocator.maxOrder=9` tweak does not fix a missing/corrupt class; it only changes allocator settings.

### 3. What to do

1. Download the official dist for a current **0.14.x** (or at least stock 0.13.6 `glowroot.jar` to compare).  
2. Attach with `-javaagent:` only; keep it outside the webapp classpath.  
3. Confirm the file checksum / that it opens as a valid zip (`jar tf glowroot.jar | findstr JdkLogger`).  
4. If you must ship a custom-branded agent, rebuild from upstream so shaded Netty (and logging) classes are complete — the errors above are consistent with a bad custom build.

Stock Glowroot 0.13.x / 0.14.x is routinely used with Spring Boot 2.x via `-javaagent`; there isn’t a known “2.5.12 hard incompatibility” matching this stack.

### Status

Opened **2022-05**, **no follow-up**, custom jar name, classic corrupt/misplaced agent symptoms. I’d close as **needs-info / environmental (custom or corrupt agent jar)** unless someone can reproduce with the **official** `glowroot.jar` from GitHub Releases.

@nowheresly — I can’t close issues; please close if you agree.
