### ISSUE TITLE
NoClassDefFoundError java.lang.management.ManagementFactory with Wildfly 26

### ISSUE THREAD

**Issue by wd0504** [glowroot/glowroot#956]
Hello,

We tried to get Glowroot working with latest Wildfly (26.1.2.Final) and bumped into a stacktrace below. This could be replicated with a simple one-servlet war deployed on fresh Wildfly with javaagent added.

For whatever reason changing the `xmlns="urn:jboss:module:1.9"` to `xmlns="urn:jboss:module:1.7"` in `module.xml` of `modules/system/layers/base/javax/servlet/api/main` seemed to fix the issue. We have no idea why but what lead to this discovery was that the issue doesn't exist in Wildfly 22 but does in Wildfy 23 and these were changed in between. (Also according to some sources 22 was the last one with Java EE8 while 23 was the first with Jakarta EE8 if that could be the reason.)

So without digging any deeper (as we feel like running out of competence) do you have any ideas if this is possibly an incompatibility or a configuration issue?

Versions used

Wildfly 26.1.2.Final
Java openjdk 11.0.16 2022-07-19
Glowroot 0.14.0-beta.3

Stacktrace
```
12:49:09,198 INFO  [stdout] (default task-1) 2022-10-11 12:49:09.197 ERROR o.g.a.p.servlet.ContainerStartup_ - could not create platform mbean server: java/lang/management/ManagementFactory
12:49:09,198 INFO  [stdout] (default task-1) java.lang.NoClassDefFoundError: java/lang/management/ManagementFactory
12:49:09,198 INFO  [stdout] (default task-1) 	at javax.servlet.api@2.0.0.Final//org.glowroot.agent.plugin.servlet.ContainerStartup_.initPlatformMBeanServer(ContainerStartup.java:58)
12:49:09,199 INFO  [stdout] (default task-1) 	at javax.servlet.api@2.0.0.Final//org.glowroot.agent.plugin.servlet.ServletAspect$ServiceInitAdvice_.onBefore(ServletAspect.java:439)
12:49:09,199 INFO  [stdout] (default task-1) 	at javax.servlet.api@2.0.0.Final//javax.servlet.GenericServlet.init(GenericServlet.java)
12:49:09,199 INFO  [stdout] (default task-1) 	at io.undertow.servlet@2.2.19.Final//io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:117)
12:49:09,199 INFO  [stdout] (default task-1) 	at org.wildfly.security.elytron-web.undertow-server-servlet@1.10.1.Final//org.wildfly.elytron.web.undertow.server.servlet.RunAsLifecycleInterceptor.doIt(RunAsLifecycleInterceptor.java:70)
12:49:09,199 INFO  [stdout] (default task-1) 	at org.wildfly.security.elytron-web.undertow-server-servlet@1.10.1.Final//org.wildfly.elytron.web.undertow.server.servlet.RunAsLifecycleInterceptor.init(RunAsLifecycleInterceptor.java:76)
12:49:09,199 INFO  [stdout] (default task-1) 	at io.undertow.servlet@2.2.19.Final//io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:103)
12:49:09,200 INFO  [stdout] (default task-1) 	at io.undertow.servlet@2.2.19.Final//io.undertow.servlet.core.ManagedServlet$DefaultInstanceStrategy.start(ManagedServlet.java:309)
12:49:09,200 INFO  [stdout] (default task-1) 	at io.undertow.servlet@2.2.19.Final//io.undertow.servlet.core.ManagedServlet.forceInit(ManagedServlet.java:212)
12:49:09,200 INFO  [stdout] (default task-1) 	at io.undertow.servlet@2.2.19.Final//io.undertow.servlet.handlers.ServletChain.forceInit(ServletChain.java:130)
12:49:09,200 INFO  [stdout] (default task-1) 	at io.undertow.servlet@2.2.19.Final//io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:63)
12:49:09,200 INFO  [stdout] (default task-1) 	at io.undertow.servlet@2.2.19.Final//io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
12:49:09,200 INFO  [stdout] (default task-1) 	at org.wildfly.security.elytron-web.undertow-server@1.10.1.Final//org.wildfly.elytron.web.undertow.server.ElytronRunAsHandler.lambda$handleRequest$1(ElytronRunAsHandler.java:68)
12:49:09,200 INFO  [stdout] (default task-1) 	at org.wildfly.security.elytron-base@1.19.1.Final//org.wildfly.security.auth.server.FlexibleIdentityAssociation.runAsFunctionEx(FlexibleIdentityAssociation.java:103)
12:49:09,201 INFO  [stdout] (default task-1) 	at org.wildfly.security.elytron-base@1.19.1.Final//org.wildfly.security.auth.server.Scoped.runAsFunctionEx(Scoped.java:161)
12:49:09,201 INFO  [stdout] (default task-1) 	at org.wildfly.security.elytron-base@1.19.1.Final//org.wildfly.security.auth.server.Scoped.runAs(Scoped.java:73)
12:49:09,201 INFO  [stdout] (default task-1) 	at org.wildfly.security.elytron-web.undertow-server@1.10.1.Final//org.wildfly.elytron.web.undertow.server.ElytronRunAsHandler.handleRequest(ElytronRunAsHandler.java:67)
12:49:09,201 INFO  [stdout] (default task-1) 	at io.undertow.servlet@2.2.19.Final//io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68)
12:49:09,201 INFO  [stdout] (default task-1) 	at io.undertow.servlet@2.2.19.Final//io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:117)
12:49:09,201 INFO  [stdout] (default task-1) 	at io.undertow.servlet@2.2.19.Final//io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
12:49:09,201 INFO  [stdout] (default task-1) 	at io.undertow.core@2.2.19.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
12:49:09,201 INFO  [stdout] (default task-1) 	at io.undertow.core@2.2.19.Final//io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
12:49:09,202 INFO  [stdout] (default task-1) 	at io.undertow.servlet@2.2.19.Final//io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
12:49:09,202 INFO  [stdout] (default task-1) 	at io.undertow.core@2.2.19.Final//io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
12:49:09,202 INFO  [stdout] (default task-1) 	at org.wildfly.security.elytron-web.undertow-server-servlet@1.10.1.Final//org.wildfly.elytron.web.undertow.server.servlet.CleanUpHandler.handleRequest(CleanUpHandler.java:38)
12:49:09,202 INFO  [stdout] (default task-1) 	at io.undertow.core@2.2.19.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
12:49:09,202 INFO  [stdout] (default task-1) 	at org.wildfly.extension.undertow@26.1.2.Final//org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
12:49:09,202 INFO  [stdout] (default task-1) 	at io.undertow.core@2.2.19.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
12:49:09,202 INFO  [stdout] (default task-1) 	at org.wildfly.extension.undertow@26.1.2.Final//org.wildfly.extension.undertow.deployment.GlobalRequestControllerHandler.handleRequest(GlobalRequestControllerHandler.java:68)
12:49:09,202 INFO  [stdout] (default task-1) 	at io.undertow.servlet@2.2.19.Final//io.undertow.servlet.handlers.SendErrorPageHandler.handleRequest(SendErrorPageHandler.java:52)
12:49:09,203 INFO  [stdout] (default task-1) 	at io.undertow.core@2.2.19.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
12:49:09,203 INFO  [stdout] (default task-1) 	at io.undertow.servlet@2.2.19.Final//io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:275)
12:49:09,203 INFO  [stdout] (default task-1) 	at io.undertow.servlet@2.2.19.Final//io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:79)
12:49:09,203 INFO  [stdout] (default task-1) 	at io.undertow.servlet@2.2.19.Final//io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:134)
12:49:09,203 INFO  [stdout] (default task-1) 	at io.undertow.servlet@2.2.19.Final//io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:131)
12:49:09,203 INFO  [stdout] (default task-1) 	at io.undertow.servlet@2.2.19.Final//io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
12:49:09,203 INFO  [stdout] (default task-1) 	at io.undertow.servlet@2.2.19.Final//io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
12:49:09,203 INFO  [stdout] (default task-1) 	at org.wildfly.extension.undertow@26.1.2.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1544)
12:49:09,204 INFO  [stdout] (default task-1) 	at org.wildfly.extension.undertow@26.1.2.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1544)
12:49:09,204 INFO  [stdout] (default task-1) 	at org.wildfly.extension.undertow@26.1.2.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1544)
12:49:09,204 INFO  [stdout] (default task-1) 	at org.wildfly.extension.undertow@26.1.2.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1544)
12:49:09,204 INFO  [stdout] (default task-1) 	at io.undertow.servlet@2.2.19.Final//io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:255)
12:49:09,204 INFO  [stdout] (default task-1) 	at io.undertow.servlet@2.2.19.Final//io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:79)
12:49:09,204 INFO  [stdout] (default task-1) 	at io.undertow.servlet@2.2.19.Final//io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:100)
12:49:09,204 INFO  [stdout] (default task-1) 	at io.undertow.core@2.2.19.Final//io.undertow.server.Connectors.executeRootHandler(Connectors.java:387)
12:49:09,204 INFO  [stdout] (default task-1) 	at io.undertow.core@2.2.19.Final//io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:852)
12:49:09,204 INFO  [stdout] (default task-1) 	at org.jboss.threads@2.4.0.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
12:49:09,205 INFO  [stdout] (default task-1) 	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
12:49:09,205 INFO  [stdout] (default task-1) 	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
12:49:09,205 INFO  [stdout] (default task-1) 	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1348)
12:49:09,205 INFO  [stdout] (default task-1) 	at org.jboss.xnio@3.8.7.Final//org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1282)
12:49:09,205 INFO  [stdout] (default task-1) 	at java.base/java.lang.Thread.run(Thread.java:829)
12:49:09,205 INFO  [stdout] (default task-1) Caused by: java.lang.ClassNotFoundException: java.lang.management.ManagementFactory from [Module "javax.servlet.api" version 2.0.0.Final from local module loader @10acd6 (finder: local module finder @61dde151 (roots: **))]
12:49:09,205 INFO  [stdout] (default task-1) 	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:200)
12:49:09,205 INFO  [stdout] (default task-1) 	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:410)
12:49:09,205 INFO  [stdout] (default task-1) 	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:398)
12:49:09,206 INFO  [stdout] (default task-1) 	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:116)
12:49:09,206 INFO  [stdout] (default task-1) 	... 52 common frames omitted
```

**Comment by mauromol** [comment]
See #1025

**Comment by Never-lab** [comment]
﻿Duplicate of **#1025**: servlet plugin ``ContainerStartup.initPlatformMBeanServer()`` runs under WildFly’s ``javax.servlet.api`` / ``jakarta.servlet.api`` module TCCL, which often lacks ``java.management`` → ``NoClassDefFoundError: ManagementFactory``.

Workaround: add ``<module name="java.management"/>`` (optional ok) to that servlet API ``module.xml``. Changing ``urn:jboss:module:1.9`` → ``1.7`` was an accidental side effect, not the real fix.

@nowheresly — please close as duplicate of #1025.
