### ISSUE TITLE
IncompatibleClassChangeError on Payara 173

### ISSUE THREAD

**Issue by bit-ionutursuleanu** [glowroot/glowroot#262]
After updating Payara 172 to 173 the following error appears while preparing a jdbc statement:
````
java.lang.IncompatibleClassChangeError: Class com.sun.proxy.$Proxy313 does not implement the requested interface org.glowroot.agent.plugin.jdbc.StatementAspect$HasStatementMirror
	at org.glowroot.agent.plugin.jdbc.ConnectionAspect$PrepareAdvice.onReturn(ConnectionAspect.java:78)
	at com.sun.gjc.spi.jdbc40.ProfiledConnectionWrapper40.prepareStatement(ProfiledConnectionWrapper40.java:316)
	at org.compiere.util.CPreparedStatement.<init>(CPreparedStatement.java:105)
````

**Comment by trask** [comment]
Hi @bit-ionutursuleanu, thanks for reporting this!  I'll try to put out a fix tomorrow.

**Comment by trask** [comment]
Thanks again for reporting this.  I think it should be fixed now in the latest snapshot release [glowroot-agent-0.9.25-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.9.25-SNAPSHOT).

**Comment by bit-ionutursuleanu** [comment]
Hi,
Just tested and it works.  Thanks
